<?php

namespace AppBundle\Repository;

/**
 * FuncionalidadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuncionalidadeRepository extends \Doctrine\ORM\EntityRepository
{
}
