<?php

namespace AppBundle\Repository;

/**
 * GrupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoRepository extends \Doctrine\ORM\EntityRepository
{
}
