<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Usuario;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @inheritdoc
     */
    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        if (is_null($orderBy)) {
            $orderBy = ['dataHora' => 'desc'];
        }
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }

    /**
     * @param Usuario $u
     * @return int
     */
    public function ticketsAbertosPor(Usuario $u): int
    {
        return intval($this->getEntityManager()
            ->createQuery('SELECT COUNT(t) FROM AppBundle:Ticket t WHERE t.usuarioCriador = ?1')
            ->setParameter(1, $u)
            ->getResult()[0][1]);
    }

    public function ticketsSobResponsabilidade(Usuario $u): int
    {
        return intval($this->getEntityManager()
            ->createQuery('SELECT COUNT(t) FROM AppBundle:Ticket t WHERE t.atendenteResponsavel = ?1')
            ->setParameter(1, $u)
            ->getResult()[0][1]);
    }
}
