<?php

namespace AppBundle\Repository;

/**
 * TokenSenhaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenSenhaRepository extends \Doctrine\ORM\EntityRepository
{
}
